FROM jupyter/datascience-notebook:latest

ENV JUPYTER_ENABLE_LAB yes
ENV JUPYTER_PASSWORD   passwd
ENV TZ                 Asia/Tokyo

COPY entrypoint.sh /entrypoint.sh

VOLUME /home/jovyan

CMD ["/entrypoint.sh"]
