FROM jupyter/datascience-notebook:latest

USER root

RUN apt-get update &&\
    apt-get install -y --no-install-recommends \
    sudo \
    whois &&\
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*
RUN cp -n -r --preserve=mode /home/jovyan/. /etc/skel

ENV JUPYTER_ENABLE_LAB yes

ENV JUPYTER_USER       reluser
ENV JUPYTER_PASSWORD   relpasswd
ENV JUPYTER_GROUP      relgroup
ENV JUPYTER_HOME       /home/reluser
ENV JUPYTER_UID        1001
ENV JUPYTER_GID        1001
ENV JUPYTER_GRANT_SUDO nopass

ENV TZ=Asia/Tokyo

COPY entrypoint.sh /entrypoint.sh

VOLUME /home

ENTRYPOINT ["/entrypoint.sh"]
